hostname: "rpi3b01"
k3os:
  k3s_args:
  - server
  - --disable
  - traefik
  - --disable
  - servicelb
  - --disable
  - local-storage
  - --write-kubeconfig
  - /var/lib/rancher/k3s/kubeconfig.yml
  - --tls-san
  - rpi3b01
  - --node-name
  - rpi3b01
  - --kube-controller-arg
  - terminated-pod-gc-threshold=15
  - --kube-apiserver-arg
  - requestheader-allowed-names=system:auth-proxy,kubernetes-proxy
  - --kube-apiserver-arg
  - external-hostname=rpi3b01
